export default {
  reviews: "testimonials",
  about_product: "about us",
  conditions: "terms",
  faq: "faq",
  contacts: "contacts",
  registration: "registration",
  log_in: "login",
  cond_main_title: "Terms of the affiliate program SpinBet Partners",
  cond_main_text: `LAST UPDATED: 26.07.23<br><br>
  Sprut Group B.V., a company registered in Curacao, with registration number149459 and registered office: Abraham Mendez Chumaceiro Boulevard 03, Willemstad, Curacao, referred to in this Agreement (“SpinBet Partners”), (“Program”)<br><br>
  These terms and conditions ("Agreement") govern your participation in the SpinBet Partners affiliate program ("Program") as an affiliate ("Affiliate"). The Partner undertakes to comply with this Agreement and the schedules and agrees with them and the amendments made by the Program.<br><br><br>
  Terms<br><br>
  For the purposes of this Agreement, the following terms are used in the text:<br><br>
  Brand traffic: traffic generated by requests containing the names of affiliate program projects in various ways, including those with errors (typos);<br><br>
  Motivated traffic: these are users who have agreed to perform any action that qualifies as a conversion in exchange for money or any other type of promotion;<br><br>
  GGR: gross gaming income, calculated as the sum of all bets minus the sum of all winnings;<br><br>
  Payment System Commissions: payment systems commission;<br><br>
  Royalty of Game Providers: commission of game providers;<br><br>
  NGR: net gaming income;<br><br>
  RevShare: Affiliate commission percentage;<br><br>
  CPA: payment for specific actions of the client on the Program website;<br><br>
  Offer: a commercial offer posted on the Program website, available to Partners under individual commercial and territorial conditions for each offer.
  `,
  cond_title1: `1. SpinBet Partners Terms and Conditions:`,
  cond_title2: `2. Traffic, sources, and restrictions:`,
  cond_title3: `3. Commissions, negative balance carryover, and sub-partnerships.`,
  cond_title4: `4. Use of promotional materials`,
  cond_title5: `5. Fraud and violation of the rules of cooperation`,
  cond_title6: `6. Procedure and terms of payment`,
  cond_title7: `7. Non-competition`,
  cond_title8: `8. The right to enforce the contract`,
  cond_title9: `9. Disclaimer`,
  cond_title10: `10. Final provisions`,
  cond_text1: `1.1 Principles of work, safety of data and account:<br>
  <br>
   (a) By registering in the Affiliate Program under the terms of this Agreement, the Partner confirms his acceptance of the terms of this Agreement.<br>
  <br>
  (b) By accepting the SpinBet Partners Terms and Conditions, the Affiliate confirms that he/she is 18 years of age or older.<br>
  <br>
  1.2 The Program may, at its sole discretion, confirm or otherwise verify the validity and accuracy of any information provided by the Partner during the registration. If at any time the Program determines, in its sole discretion, that the information provided by the Partner during the registration is misleading, inaccurate, or untrue, the Program may restrict, disable or terminate the Partner's account, access, and use by the Partner of the Program and/or any the benefits received from the Partner's participation in the Program; The Program may also withhold the payment of any commissions and/or other funds that may or may not be payable to the Affiliate.<br>
  <br>
  1.3. Login and password are created to access the system of the affiliate program SpinBet Partners.<br>
  <br>
  1.4. The responsibility for protecting this data from third parties lies solely with the Partner. SpinBet Partners is not responsible for the safety of this confidential data. The Affiliate Program recommends using two-factor authentication to secure your account.<br>
  <br>
  1.5. The SpinBet Partners program may refuse to cooperate with any Partner without giving reasons.<br>
  <br>
  1.6. Selling or transferring accounts to third parties without prior approval from the Affiliate Program is strictly prohibited.<br>
  <br>
  1.7. SpinBet Partners Affiliate Program reserves the right to revise and change the rules of the Affiliate Program without the consent of the Partner and without prior notice.<br>
  <br>
  1.8. The rules published on the Program website are considered valid. The chronology of changes in the rules of the Affiliate Program is not maintained.<br>
  <br>
  1.9. The parties intend under this Agreement to establish a relationship between the Program and the Partner. Still, neither party intends to create a joint venture or make the Partner in any sense an agent or employee of the Program. The parties expressly agree that they are independent contractors and that this Agreement does not in any way create a joint venture nor have the parties granted each other any right or authority to incur or create any obligation of liability, express or implied, on behalf of each other, or bind the other party in any way.<br>
  <br>
  1.10. Affiliate shall not create or assume on behalf of the Program or on its own behalf any obligations, express or implied, or act or intend to act as its agent or representative for any purpose, and Affiliate shall not have the right to position himself as having such authority.<br>
  <br>
  1.11. The Partner is solely responsible for the development, operation, and maintenance of the Partner's website, as well as for all materials that appear on the Partner's website. Such responsibilities include, but are not limited to, the technical operation of the Partner's website and all related equipment; creation and placement of reviews, descriptions, and links to products on the Partner's website and linking these links to the Program website; the accuracy and correctness of the materials posted on the Partner's website; and ensuring that materials posted on the Affiliate's website do not infringe or infringe on the rights of any third party, or be defamatory or otherwise violate any applicable law. The program declines any responsibility for such cases. Except as provided in this Section, the Affiliate may not sublease, rent, sell, resell, or outsource any Proposal, and any attempt to do so will be invalid.<br>
  <br>
  1.12. The Partner may be granted a non-exclusive, non-transferable license for the term of this Agreement to use the trade name of the Program, trademarks, service marks, logos, and any other designations (together - Intellectual Property) only with the written consent of the Program Representative solely in connection with the placement of advertising materials on Partner website. This license may not be sublicensed, assigned, or otherwise transferred by the Affiliate. Affiliate's right to use the Intellectual Property is limited by this license and arises only from this license. Affiliate shall not assert invalidity, unenforceability or challenge the right to the Intellectual Property in any action or proceeding of any kind or nature, and shall not take any action that may infringe the Program's rights to the Intellectual Property, create a similar, otherwise weaken its validity or harm the reputation that accompanies it.<br>
  `,
  cond_text2: `2.1. The Affiliate Program reserves the right to request information about the Partner's traffic sources at any time.<br>
  <br>
  2.2. If the Affiliate refuses to provide information about the sources through which he/she advertises the casino, the Affiliate Program reserves the right to suspend payments to the Affiliate.<br>
  <br>
  2.3. For websites, you need to specify a URL (or an alternative way to the domain), for media/arbitrage traffic - an example ad and a screenshot of the advertising account, for email newsletters - add an email address support@spinbet.partners to the mailing list, as well as show the texts and templates of letters, for public publications on social networks, streaming channels or mobile applications - use the correct links.<br>
  <br>
  2.4. If the advertisement uses languages &#8203;&#8203;not used in the Affiliate Program, the Partner is obliged to translate it upon request. The Affiliate Program uses the &ldquo;Last cookie wins&rdquo; rule. This means that the player will be assigned to the Partner whose advertisement led to the player's registration with SpinBet Partners for the last time.<br>
  <br>
  2.5. The SpinBet Partners Affiliate Program allows Partners to send emails to players using the Partner's own contact databases, only if the source of this data is indicated. The text of the e-mail must be approved in advance by the Affiliate Program.<br>
  <br>
  2.6. Engaging players using spam mailings is prohibited. Upon detection of such mailing, the Affiliate Program may close the Partner's personal account in the SpinBet Partners system without paying out the funds earned and stored on the account.<br>
  <br>
  2.7. Branded traffic Affiliates are limited to the Affiliate Program through standard commission programs.<br>
  <br>
  2.8. For the Spinbetter.com RevShare project, the commission for Branded traffic is 20%.<br>
  <br>
  2.9. Also under the definition of branded traffic are sites with a copied or similar design to the original. It is strictly forbidden to use the names of the Affiliate Program projects or the names of the Affiliate Projects with numbers that may look like a mirror of the project for branded traffic, such as Spinbetter1, SpinBetter2, Spinbetter123, etc.<br>
  <br>
  2.10. If the Affiliate wants to use branded traffic, it is necessary to contact the Affiliate Program and agree on the conditions under which the Affiliate Program can accept this traffic. In case of deliberate use of standard commissions for branded traffic and concealment of this information, the Affiliate Program reserves the right to suspend cooperation with the Partner.<br>
  <br>
  2.11. Motivated traffic is prohibited by the Affiliate Program. If such traffic is detected, the Affiliate Program reserves the right to close the Affiliate's account without warning and payment of any funds stored in the account.<br>
  `,
  cond_text3: `3.1 The standard commission program is dynamic RevShare from 20% to 55%, which is calculated by the formula:<br>
  <br>
  [(Bets &ndash; Wins) &ndash; Payment System Commissions &mdash; Royalty of Game Providers] * % RevShare = NGR * % RevShare.<br>
  <br>
  3.2. In the SpinBet Partners affiliate program, you can work on CPA and Hybrid programs (CPA + RevShare). These programs are set on an individual basis by agreement between the Affiliate Program and the Affiliate and may be canceled at any time within 24 hours after the Affiliate has been notified.<br>
  <br>
  3.3. If an Affiliate operates on the RevShare flat commission model and fails to attract new players to affiliate program projects for 1 month or more, his/her RevShare flat commission may be changed to the RevShare minimum commission program of 20% or one that matches his/her dynamic grid.<br>
  <br>
  3.4. At the beginning of cooperation, representatives of the affiliate program can offer the partner a RevShare deal - 50% to start working, within 1-2 months. At the end of the month, the conditions can be revised up or down based on the volume of traffic in accordance with the dynamic grid.<br>
  <br>
  Single dynamic RevShare grid for sports betting and casino:<br><br>
  <div class="terms-grid" style="display: grid;
  grid-template-columns: repeat(2, 1fr);
  grid-template-rows: repeat(7, 1fr);
  grid-column-gap: 0px;
  grid-row-gap: 0px;
  border: 1px solid #fff;">
  <div style="display:flex; align-items:center;justify-content:center; border:1px solid #fff;">0-9</div>
  <div style="display:flex; align-items:center;justify-content:center; border:1px solid #fff;">20%</div>
  <div style="display:flex; align-items:center;justify-content:center; border:1px solid #fff;">10-24</div>
  <div style="display:flex; align-items:center;justify-content:center; border:1px solid #fff;">25%</div>
  <div style="display:flex; align-items:center;justify-content:center; border:1px solid #fff;">25-35</div>
  <div style="display:flex; align-items:center;justify-content:center; border:1px solid #fff;">30%</div>
  <div style="display:flex; align-items:center;justify-content:center; border:1px solid #fff;">35-44</div>
  <div style="display:flex; align-items:center;justify-content:center; border:1px solid #fff;">35%</div>
  <div style="display:flex; align-items:center;justify-content:center; border:1px solid #fff;">45-54</div>
  <div style="display:flex; align-items:center;justify-content:center; border:1px solid #fff;">40%</div>
  <div style="display:flex; align-items:center;justify-content:center; border:1px solid #fff;">55-99</div>
  <div style="display:flex; align-items:center;justify-content:center; border:1px solid #fff;">45%</div>
  <div style="display:flex; align-items:center;justify-content:center; border:1px solid #fff;">100+</div>
  <div style="display:flex; align-items:center;justify-content:center; border:1px solid #fff;">50%</div>
</div>
<br><br>
  3.5. If during the billing period, there were winnings of players that exceeded their deposits, that is, if the players engaged by the Partner caused losses to the Casino, the Partner's income for this billing period will be equal to zero.<br>
<br>
3.6. If there is a negative balance on the Partner's account in the current billing period, it can be rolled over to the next billing period. In such cases, the next billing period starts with a negative value.<br>
<br>
 3.7. Negative balance transfer can be disabled if, during the 1st month, the traffic and activity of the player meet these conditions:<br>
<br>
Number of registrations &mdash; 1000+<br>
A number of players with first deposits (FTD) - 100+<br>
The total amount of deposits &mdash; $20,000<br>
Number of players with deposits - 200<br>
<br>
If one of the indicators is less than these criteria, then the transfer of the negative balance will be re-enabled for the Partner.<br>
<br>
3.8. If an Affiliate has referred a person who wants to become a new Affiliate (sub-affiliate) and cooperate with the SpinBet Partners Affiliate Program, the Affiliate who has referred a new Affiliate will receive referral bonuses.<br>
<br>
3.9. The amount of referral bonuses is 2-5% of the NGR earnings of all previously listed sub-partners for the billing period.<br>
<br>
3.10. Any violation by the Sub-Partner of the provisions of this Agreement will be considered a violation of this Agreement by the Partner.<br>

  `,
  cond_text4: `4.1. The use of advertising materials (graphics, videos, logos, layout elements, texts) of the Projects of the Affiliate Program in order to promote the Affiliate's own projects is prohibited.<br>
  <br>
  4.2. In case of violation of this rule, the Affiliate's account may be blocked without any notice.<br>
  <br>
  4.3. It is forbidden to change the logos of the Affiliate Program Projects in any way, including changing fonts, colors, or any other changes that contradict the Brand Book. If necessary, the Partner can request the Brand Book from his personal Manager.<br>
  <br>
  4.4. The Affiliate Program provides its Partners with various text and graphic materials (by prior agreement). Partners have the right to use any information from the casino website and from the casino's personal account, provided that it is paraphrased. If the text is copied from the casino website &quot;as is&quot;, the Affiliate Program may terminate the partnership with the Affiliate or treat his/her traffic as branded.<br>
  <br>
  4.5. Affiliates are prohibited from promoting the Projects of the Affiliate Program by sending spam by e-mail, contextual advertising mentioning the brands of the Projects of the Affiliate Program, and advertising such as ClickUnder / PopUnder. If such activity is detected, the Affiliate's personal account will be restricted, any accumulated funds and commissions will be withheld. It is also forbidden to use false information about the casino and bonuses.<br>
  <br>
  4.6. The affiliate program may require the replacement of outdated links, screenshots, logos, and other promotional materials; in the event that the Affiliate refuses to replace them, the Affiliate Program may defer payment for an indefinite period of time until the required changes are made.<br>
  <br>
  4.7. Information about SpinBetter.com and any other projects of the Affiliate Program in the Affiliate's reviews must be true. In case of an indication of false information, different from the information on the project websites, the Affiliate Program may suspend cooperation with the Partner<br>
  `,
  cond_text5: `5.1. Affiliates are prohibited from owning and using their personal accounts in any Projects that belong to the SpinBet Partners Affiliate Program through their own referral link. In case of violation of this rule, both accounts of the Partner will be blocked, and funds from both accounts will be debited.<br>
  <br>
  5.2. Such decisions are not subject to challenge. This rule also applies to members of the Partner's family and his friends, relatives, employees, contractors, and other persons with whom the Partner has a close relationship.<br>
  <br>
  5.3. The Affiliate Program reserves the right to change the Partner's balance by the amount that was lost by the casino as a result of the fraudulent actions of players attracted by the Partner. The partner's balance can be changed for this reason within an unlimited period of time after the detection of fraud.<br>
  <br>
  5.4. The Affiliate Program has the right not to pay the Affiliate the profit received under the CPA model in cases where the Affiliate attracts fake clients (players with multiple accounts, motivated or fraudulent traffic, etc.). If the administration of the Affiliate Program notices any untypical behavior of players (for example, an atypically high percentage of players who do not return to the project after CPA qualification), the partner's income will be recalculated in accordance with the standard RevShare commission.<br>
  <br>
  5.5. Deliberately providing the Affiliate Program with false information about traffic sources may lead to termination of cooperation.<br>
  <br>
  5.6. The Affiliate Program has the right to terminate the Agreement and immediately block the Affiliate's account by sending a written notice of termination of cooperation to the Affiliate in the event of insults against the Affiliate managers, support and administration of the Affiliate Program and/or its projects; misleading and/or false public statements about the Affiliate Program and/or its projects. Misrepresentation and/or false public statements may mean text, action, or other manipulation of information by the Partner, not supported by any evidence (screenshots, links, etc.). Texts, images, or data in any other digital form containing offensive language or any other direct/indirect insults may be considered as an insult in relation to the support and administration of the Affiliate Program and/or its projects.<br>
  <br>
  5.7. If the administration of the Projects of the Affiliate Program or the administration of the Affiliate Program has reason to suspect the Partner of violating the rules of the Affiliate Program during cooperation, his account may be blocked, and payments may be postponed for an indefinite period until the circumstances are clarified. If the check concludes that the fact of violation of the rules is confirmed, the Affiliate program has the right not to make payments to the Partner.<br>
  <br>
  5.8. In case of disagreement, the Partner must provide the Affiliate Program with arguments in favor of his point of view and his vision of solving the existing situation. The SpinBet Partners affiliate program is ready to consider all the arguments presented by the Partner and find a solution that is as honest as possible from the point of view of both parties. The decision of the Affiliate Program cannot be challenged.<br>
  `,
  cond_text6: `6.1. The Program will pay the Partner a commission calculated in accordance with the payment terms specified in each Offer posted by the Program on the Program Website. The Program applies NET 60, NET 30, NET 15, or NET 7 payment plans at its sole discretion, depending on the volume and quality of traffic sent by the Partner, unless otherwise agreed by both parties.<br>
  <br>
  6.2. Regardless of the chosen payment method (for example, Neteller, Skrill, etc.). The Partner must provide the Program with their actual bank details.<br>
  <br>
  6.3. The Affiliate Program makes payments only to the details that are specified in the Partner's personal account. The details can be changed in the partner's personal account independently. The Affiliate Program is not responsible if the payment was made using the details from the Partner's personal account, but turned out to be invalid or incorrect. The Partner bears full, sole, and independent responsibility for the relevance of the data entered by him. If the Affiliate wants to change the payment details, he must report this without fail to mail support@spinbet.partners from the mail under which he registered on the Affiliate Program website. If a message about this was not received by mail or the message was received from another mail that does not belong to the registered account, then the request will not be taken into account and will be canceled.<br>
  <br>
  6.4 The Program may, in its sole discretion and from time to time, decide to transfer some or all of the Commission to the Affiliate before receiving payment from the Client, but in no case is obliged to do so.<br>
  <br>
  6.5. Commissions will only be paid to the Affiliate upon receipt by the Program of payment from the Client in respect of such Offer published in the Program's online reporting system.<br>
  <br>
  6.6 The Affiliate receives a commission in the Affiliate Program, which is calculated as a percentage of the casino's net income from players referred by the Affiliate. The partner can choose the most profitable commission model for him.<br>
  <br>
  6.7. The minimum withdrawal amount from the Partner's account is 50 EUR for payment systems and 500 EUR for a bank transfer.<br>
  <br>
  6.8. Payment details can be changed no later than 5 working days before the end of the billing period and before the end of payments. The administration may delay payments to partners whose players show suspicious activity, or to new partners for a period of time that the Affiliate Program deems appropriate for verification.<br>
  <br>
  6.9. If the Partner refers less than 5 players before the first withdrawal, additional verification of these players may be carried out.<br>
  <br>
  6.10. The Affiliate Program pays lifetime commissions on all commissions as long as the Affiliate fulfills all of its obligations and does not cause any reputational or financial damage to the Affiliate Program or its projects.<br>
  `,
  cond_text7: `7.1 During the term of this Agreement and for a period of six (6) months thereafter, Affiliate shall not attempt in any way to bring the Program into disrepute, and in particular, Affiliate shall not, directly or indirectly: 1) solicit, or attempt to solicit or solicit, work other than the Program; (2) induce or attempt to induce any of the Program's employees to change jobs for employment with a Program Partner or competitor; or (3) directly or indirectly enter into any agreement or contract, whether in writing or otherwise, with any Client or otherwise provide services to any third party for the ultimate benefit of a Client who, in the opinion of the Program, may compete with any services provided by the Program to that Client.`,
  cond_text8: `8.1. The Program's failure to enforce the Affiliate's strict compliance with any provision of this Agreement will not constitute a waiver of the Program's right to subsequently enforce such provision or any other provision of this Agreement. No changes by employees or Partners, as well as additions, deletions, or additions to this Agreement, will be recognized by the Program until the moment of publication on the site. None of our employees or agents has the authority to make or agree to any change or modification to this Agreement or its terms.`,
  cond_text9: `9.1. The Program disclaims all warranties, conditions, representations, and indemnifications with respect to any liability, express or implied (including, without limitation, any warranties of profitability, satisfactory quality, merchantability, fitness for a particular purpose, title, and non-infringement).<br>
  <br>
  9.2. Notwithstanding any other provision of this Agreement, the Program further disclaims all obligations and liability on the part of the Program and those to whom it is legally liable for any damages, including, but not limited to indirect and special damages, attorneys' and experts' fees, and legal costs (even if the Program has been advised of the possibility of such damages, fees or costs) arising out of or in connection with this Agreement. Under no circumstances will the Program be liable to the Partner for any indirect, indirect, special, punitive or incidental damages or loss of profits of the Partner or its successors in title (including, without limitation, claims for loss of reputation, use of or reliance on the services provided under this Agreement, stop other work, or damage other assets) arising from the breach or non-performance of express or implied warranties, breach of agreement, misrepresentation, negligence, liability for tort, or otherwise.<br>
  <br>
  9.3. Without limiting the foregoing, the Program shall not be liable for any failure or delay resulting from any act of God, fire, flood, war, riot, earthquake, power outage, riot, explosion, embargo, strike, lawful or illegal action, labor shortage or materials, interruption of transportation of any kind, slowdown, action or inaction of the Partner or third parties, the equipment or software of the Partner and/or any third party equipment, or any other conditions affecting production or delivery in any way beyond the control of the Program.<br>
  `,
  cond_text10: `10.1. The Program may assign this Agreement without the prior consent of the Partner. The Partner may not assign this Agreement without the express written consent of the Program.<br>
  <br>
  10.2. The Program reserves the right to modify or supplement this Agreement at any time, for any reason or no reason at all, at its sole discretion. The most recent version of this Agreement will be posted here. Although the Program may notify the Affiliate of material changes to this Agreement, the Affiliate shall be solely responsible for keeping abreast of any such changes or additions. Any notice or other communication permitted or required by this Agreement must be in writing and delivered personally or by fax or email to the receiving party at the address provided to the Program by the Partner in his account. Any such notice will be deemed received on the date it is faxed, emailed, or delivered in person. No term or condition of this Agreement shall be deemed waived or a breach warranted unless such waiver or consent justifying the breach is in writing and signed by both parties.<br>
  <br>
  10.3. In the event that any term or obligation of this Agreement is declared by a court of competent jurisdiction to be perpetual, invalid, illegal, or unenforceable, this Agreement with respect to the remaining provisions will remain in effect.<br>
  <br>
  10.4. This Agreement will govern and be binding on the respective successors and successors of both the Program and the Partner. This Agreement constitutes the entire agreement between the parties with respect to the subject matter of this agreement and supersedes any prior or contemporaneous representations, negotiations, understandings, and agreements, whether oral or written.<br>
  <br>
  10.5. This Agreement is written and available in English and Russian. In the event of any inconsistency between the meanings of any translated versions of this agreement, the meaning of that English version shall prevail.<br>
  <br>
  10.6. The validity, interpretation, and performance of this Agreement shall be governed by the laws of Curacao.<br>
  <br>
  10.7. Any disputes arising between the Parties from this Agreement or in connection with it shall be resolved in the appropriate court of Curacao in accordance with the laws of Curacao.<br>
  `,
  faq_title: `The most asked question “What is the retention rate?”.<br/> We answer right away!`,
  faq_subtitle: `The ratio of the amount of deposits to the amount of bets — <span>1х13</span>`,
  faq_titlesub: `Reg2Dep conversion = <span>Up to 40%</span>`,
  faq_instr_title: `Our retention tools:`,
  faq_instrs: ` <li>Call center</li>
  <li>VIP managers</li>
  <li>Support department</li>
  <li>E-mail</li>
  <li>Push</li>
  <li>In-app</li>
  <li>SMS</li>
  <li>Regular draws</li>
  <li>Bonuses</li>
  <li>Promotions</li>`,
  faq_title1: `<span></span>What is the SpinBet Partners affiliate program?
  `,
  faq_title2: `<span></span>How can I become a partner?`,
  faq_title3: `<span></span>What payment models do you work with?`,
  faq_title4: `<span></span>Can I work with you on a CPA basis?`,
  faq_title5: `<span></span>What does player qualification mean?`,
  faq_title6: `<span></span>How does the priority system work for player attribution to a partner?`,
  faq_title7: `<span></span>Can I do API integration with your affiliate program?`,
  faq_title8: `<span></span>Do you have two-factor authentication?`,
  faq_title9: `<span></span>What is the minimum payout and how do I find out my balance?`,
  faq_title10: `<span></span>What is the payout frequency?`,
  faq_title11: `<span></span>How can I create referral link?`,
  faq_title12: `<span></span>Which GEOs are allowed/prohibited?`,
  faq_title13: `<span></span>What parameters are available for player analytics?`,
  faq_title14: `<span></span>Can I get advice about my traffic?`,
  faq_title15: `<span></span>What if I cannot or do not want to verify the sources of my traffic?`,
  faq_title16: `<span></span>I want to send branded traffic, what are the conditions?`,
  faq_title17: `<span></span>How is the revenue share formula calculated?`,
  faq_title18: `<span></span>I didn't find the answer to my question about how to obtain all the partnership details?`,
  faq_text1: `SpinBet Partners is a leading direct advertiser for the iGaming brand. We provide the best conditions for monetizing your traffic in the Betting & Casino verticals.`,
  faq_text2: `To become a partner, you need to have any traffic source except for fraud and incentive traffic. After that, you can register on our website, and our managers will guide you through the next steps.`,
  faq_text3: `We offer Revenue Share, Hybrid, CPA, and Flat Fee, but we are happy to discuss other payment formats.`,
  faq_text4: `Yes. We provide a test cap, and then we review your traffic. If it passes the qualification - we will increase budgets and volume.`,
  faq_text5: `Player qualification (only for partners with СРА traffic) correspondence of the player to our statistical expectations, such as minimum deposit, activity of the player, participation in the bonus program, repeated deposits, etc. Qualification depends on the offer given to you.`,
  faq_text6: `The promo code entered in the registration form has a higher priority than clicking on an affiliate link.`,
  faq_text7: `Yes, you can create an API key in your personal account to integrate with any of your systems. Our technical specialists will always be happy to help in case of difficulties.`,
  faq_text8: `Yes, with Google Authenticator. You can set it up yourself after activating your account.`,
  faq_text9: `The minimum payout is 50 USD. The current account balance is always available in your personal cabinet and is updated in real-time.`,
  faq_text10: `By default, each partner has a NET30 payment period (payment on the first Monday of each calendar month). Please contact your manager if you want to change the payout period to a different one.`,
  faq_text11: `Creating a referral link is just 4 clicks in your personal cabinet in the "Offers" section. It is only necessary to click on the button "get link", select the traffic source, select the final URL, and click "copy URL".`,
  faq_text12: `After approving the account, it would be best to ask a personal manager for the up-to-date list of the most converted and restricted GEOs.`,
  faq_text13: `You can set up analytical reports in the personal cabinet based on more than 50 metrics.`,
  faq_text14: `Yes, with enough players referred by you, our team can analyze your player base and advise helpful information that will help improve performance.`,
  faq_text15: `In this case, we reserve the right not to accept your traffic.`,
  faq_text16: `A Revenue Share of 20% is the standard rule applied to branded traffic.`,
  faq_text17: `[(Bets – Wins) – Payment System Commissions — Royalty of Game Providers] * % RevShare = NGR * % RevShare, where:
  Bets - Wins - Gross Gaming Revenue;
  Payment System Commissions - payment system fees;
  Royalty of Game Providers - game provider fees;
  NGR - net gaming revenue;
  % RevShare - your commission percentage.`,
  faq_text18: `Please contact us for more details by emailing or writing to your manager.`,
  header_subtitle: "Affiliate program<br> from direct advertiser",
  registration_button: "Registration",
  verticals_title: `Reach new heights`,
  verticals_subtitle: `in two verticals`,
  betting_and_casino: `<span>betting</span> & <span>casino</span>`,
  join_button: `join`,
  partners_program_title: `Affiliate Program`,
  partners_tile1: `Fast<br /> Support`,
  partners_tile2: `Payment models Revenue Share, CPA, HYBRID, and FLAT FEE`,
  partners_tile3: `Weekly payments by any convenient method`,
  partners_tile4: `Payout periods: NET7, NET15, NET30 or NET60.`,
  partners_tile5: `Real Time Analytics`,
  lifetime_rs: `Lifetime RS - even without new traffic<img src="./assets/images/partners-center-icon1.webp" alt="" />
  <img src="./assets/images/partners-center-icon2.webp" alt="" />`,
  bottom_partners_tile1: `Personal landing pages`,
  bottom_partners_tile2: `Banners and prerolls`,
  bottom_partners_tile3: `Promocodes`,
  bottom_partners_tile4: `Reviews and articles`,
  coop_terms_title: `transparent cooperation terms`,
  get_sale_title: `Get 50% RS from the start<br /><span>(For the first 2 month)</span>
  <img src="./assets/images/get-sale-icon1.webp" alt="" />
  <img src="./assets/images/get-sale-icon2.webp" alt="" />`,
  cpa_range: `CPA From 20$ to 150$`,
  cpa_title1: `Traffic Review`,
  cpa_title2: `Lead confirmation`,
  cpa_title3: `Time to Qualification`,
  cpa_title4: `Activity Check`,
  cpa_title5: `Player confirmation`,
  cpa_content1: `Test CAP<br />
  (50 FD)`,
  cpa_content2: `qualification<br />
  (MIN DEP)`,
  cpa_content3: `Waiting for FD<br />
  (7 days)`,
  cpa_content4: `HOLD<br />
  (14-28 days)`,
  cpa_content5: `Payout`,
  cpa_items_title: `NCO (NEGATIVE BALANCE CARRYOVER) - ACTIVE BY DEFAULT, BUT WE ARE HAPPY TO ENCOURAGE PARTNERS WITH REGULAR TRAFFIC. IF YOUR TRAFFIC MEETS THE CRITERIA BELOW - WE WILL DISABLE NCO FOR YOU.`,
  cpa_items_item1: `CRITERIA FOR DISABLING NEGATIVE BALANCE CARRYOVER:`,
  cpa_items_item2: `Number of registrations per month - 1000+`,
  cpa_items_item3: `Number of FD per month - 100+`,
  cpa_items_item4: `Number of players with deposits per month - 200+`,
  cpa_items_item5: `Total amount of deposits - 20000$+`,
  cpa_items_bottom: `<span>AFTER REACHING THE REQUIREMENTS ABOVE, THE NEGATIVE BALANCE CARRYOVER WILL BE DISABLED</span>`,
  traffic_title: `WE PAY FOR ALL TRAFFIC<br />
  <span>(Excepting the motivated, schema, and fraud)</span>`,
  traffic_tile1: `SEO`,
  traffic_tile2: `UAC`,
  traffic_tile3: `PPC`,
  traffic_tile4: `FB / Insta / Twitter`,
  traffic_tile5: `TikTok`,
  traffic_tile6: `ASO`,
  traffic_tile7: `Streamers`,
  traffic_tile8: `TG Channels`,
  traffic_tile9: `E-mail`,
  managers_title: `CHOOSE YOUR MANAGER`,
  privacy: `privacy policy`,
  terms: `terms and conditions`,
  reviews_title: `reviews`,
  privacy_main_title: `Privacy policy`,
  privacy_main_text: ` <p>Last updated: 05.06.23 
  <br/>
  <br/>
  <br/>
We are committed to making our Privacy Policy (hereinafter - Policy) transparent and understandable to you about how we use and protect your Personal Data. This Privacy Policy complies with the standards of the EU General Data Protection Regulation (GDPR).
  <br/>
  <br/>
In this Policy 
  <br/>
  <br/>
a) "we", "us" or "our" means Sprut Group B.V., (SpinBet Partners), registration number 149459, registered at Abraham Mendez Chumaceiro Boulevard 03, Curacao. 
  <br/>
  <br/>
  <br/>
b) "website" means <a href="https://spinbet.partners/" target="_blank">https://spinbet.partners/</a> 
  <br/>
  <br/>
  <br/>
This Policy explains how our company and our affiliates collect, process and disclose personal data and how such data is protected.
  <br/>
  <br/>
We also provide you with information on how we use cookies in this Policy.
  <br/>
  <br/>
If you have any questions or suggestions regarding the Privacy Policy and the use of the services we provide to you, please contact us at support@spinbet.partners.
  <br/>
  <br/>
We will periodically amend this Privacy Policy and notify you of these changes by publishing the amended terms on our platforms and websites.
  <br/>
  <br/>
Your continued use of our services following any changes to this Privacy Policy constitutes your unconditional acceptance of such changes.
  <br/>
  <br/>
We recommend that you read this Policy regularly.
  <br/>
</p>`,
  privacy_title1: `1. CONSENT TO THE PROCESSING OF PERSONAL DATA`,
  privacy_title2: `2. DATA WE COLLECT`,
  privacy_title3: `3. DATA COLLECTION AND PROCESSING TOOLS`,
  privacy_title4: `4. USE OF YOUR DATA`,
  privacy_title5: `5. DISCLOSURE OF INFORMATION`,
  privacy_title6: `6. YOUR RIGHTS REGARDING YOUR PERSONAL DATA`,
  privacy_title7: `7. COOKIES POLICY`,
  privacy_title8: `8. CONSENT TO SAFETY AUDITS`,
  privacy_title9: `9. SECURITY`,
  privacy_title10: `10. CHILD PROTECTION`,
  privacy_title11: `11. THE LENGTH OF TIME YOUR PERSONAL DATA IS STORED`,
  privacy_title12: `12. CROSS-BORDER TRANSFER`,
  privacy_title13: `13. THIRD-PARTY RELATIONSHIPS`,
  privacy_title14: `14. HOW TO CONTACT US?`,
  privacy_text1: `
  <p>Processing of your personal data with SpinBet Partners takes place only after your express state consent to processing such data (hereinafter "Consent").
  <br/>
  <br/>
Your consent to the processing of personal data may be provided by you or your representative either in writing or in the form of your actions on our website. 
  <br/>
  <br/>
WRITTEN CONSENT
  <br/>
  <br/>
In such a case, the Consent shall contain the following information:
  <br/>
  <br/>
1. surname, first name, patronymic (if any), address of the personal data subject, number of the main identity document, information on the date of issue of the specified document and issuing authority; or surname, first name, patronymic (if any), address of the personal data subject representative, number of the main identity document, information on the date of issue of the specified document and issuing authority, details of notarial power of attorney or other document confirming the authority of the representative (if consent is received from the representative;
  <br/>
2. the postal or e-mail address of SpinBet Partners receiving the consent of the personal data subject; the purpose of the processing of the personal data;
  <br/>
3. A list of the personal data that the personal data subject consents to be processed;
  <br/>
4. the name and address of the person processing the personal data on behalf of SpinBet Partners, if the processing is to be entrusted to such person;
  <br/>
5. A list of actions with personal data for which consent is given, a general description of how personal data is processed;
  <br/>
6. The period during which the personal data subject's consent is valid and how it can be withdrawn;
  <br/>
7. the signature of the data subject.
  <br/>
This consent in writing is sent to us by mail and is deemed to have been received upon our written confirmation in response to your letter.
  <br/>
  <br/>
CONSENT EXPRESSED BY ACTION
  <br/>
  <br/>
  <br/>
These are actions expressing your intention to establish a legal relationship with SpinBet Partners, not verbally or in writing, but by conduct from which such intention can be inferred.
  <br/>
  <br/>
This is the action of registering on our website using the registration window.
  <br/>
  <br/>
The processing of your personal data by SpinBet Partners does not require your consent when:
  <br/>
  <br/>
1. The processing of personal data is necessary to achieve the objectives outlined in international treaties or the laws of local jurisdictions for the exercise and performance of the functions, powers and duties assigned by laws;
  <br/>
2. The processing of personal data is necessary for the administration of justice, the execution of a judicial act, and the act of another authority or official, to be executed in accordance with local laws;
  <br/>
3. processing of personal data is necessary to protect your life, health or other vital interests;
  <br/>
4. the processing of personal data is necessary for the exercise of the rights and legitimate interests of SpinBet Partners or third parties, or for the achievement of public goals, provided that the rights and freedoms of your personal data are not violated;
  <br/>
5. processing of personal data is for statistical or other research purposes, subject to the obligation to keep your personal data confidential, except in the case of processing of personal data for marketing purposes;
  <br/>
6. your personal data is processed and made accessible by you to an unlimited number of persons;
  <br/>
7. personal data subject to publication or compulsory disclosure under the laws of local jurisdictions is processed.
  <br/>
</p>`,
  privacy_text2: `
  <p>We collect and process data that may be used for identification purposes, including, but not limited to name, date of birth, credit card or bank account information, payment information, transaction history, home or other physical address, email address, phone number, ID of the messenger you use to communicate.
  <br/>
  <br/>
  <br/>
You may be asked to provide Personal Information when using our website or services and registering an account.
  <br/>
  <br/>
This information is collected, processed and stored by us on servers, according to the requirements of the legislation of your state.
  <br/>
  <br/>
When you use our services, our servers store your unique activity log, which collects certain administrative and traffic information, including:
  <br/>
  <br/>
1. IP address,
  <br/>
2. access time,
  <br/>
3. access date,
  <br/>
4. visited web pages,
  <br/>
5. language usage,
  <br/>
6. software failure reports,
  <br/>
7. browser type.
  <br/>
  <br/>
This information is needed to provide quality services. We never collect personal data about you without your knowledge.
  <br/>
</p>`,
  privacy_text3: `
  <p>We may automatically collect certain data and receive Personal Data from you, which you provide to us as you wish, through services, communications and interactions on the SpinBet Partners website.
            <br/>
            <br/>
We may obtain Personal Data from online vendors, service providers, and from customer lists legally acquired from third-party suppliers.
            <br/>
            <br/>
In addition, we can use third-party providers to provide technical support for online transactions and account management.
            <br/>
            <br/>
We will have access to any information that you provide to such providers and third-party e-commerce services, and we will use personal data in accordance with the provisions of this Policy.
            <br/>
            <br/>
This information will be disclosed to third parties outside the company only per this Policy and the laws of your State.
            <br/>
        </p>`,
  privacy_text4: `
  <p>We use the Personal Data you provide to us to provide services including information, customer support, security, identification and verification, to process any online transactions, to assist you in participating in third-party promotions that meet certain business requirements, and for any other purpose related to the operation of our Services.
  <br/>
  <br/>
Thus, when providing services, we can share your personal information with our partners (including any other parties that have agreements with you to share your data).
  <br/>
  <br/>
Your personal information may also be used by us to provide you with:
  <br/>
  <br/>
1. promotional offers and information about our products and services;
  <br/>
2. offers and information about the products and services of our partners to expand the range of Services provided to you and to improve the quality of service to our customers.
  <br/>
  <br/>
From time to time we may ask you for information through surveys or contests. Participating in these surveys or contests is entirely voluntary and you always have a choice: to disclose or not to disclose your personal information.
  <br/>
  <br/>
The requested information may include contact information (e.g., name, mail delivery address, telephone number) and geographical information (e.g., postal code or postal address), and age.
  <br/>
  <br/>
By participating in any contest or receiving a win from us, you agree that we will use your name for promotional purposes without additional compensation unless otherwise prohibited by law.
  <br/>
</p>`,
  privacy_text5: `
  <p>We may provide information about you to companies, organizations or individuals not affiliated with SpinBet Partners if you have given us your consent for these actions.
  <br/>
  <br/>
We may disclose your Personal Information if required by law, if you have been found to have deceived or attempted to deceive us or any other user in any way (game manipulation, payment fraud, etc.) or if we are convinced that such actions are necessary to:
  <br/>
  <br/>
1. compliance with any legal issue or process that concerns us, on any of our websites, in any of our services, or in circumstances where we are legally bound;
  <br/>
2. protection of our rights or property;
  <br/>
3. to protect our users or communities.
  <br/>
</p>`,
  privacy_text6: `
  <p>You can «refuse» any advertising messages:
  <br/>
  <br/>
1. by changing the settings in your account;
  <br/>
2. by writing us an e-mail in response to the advertising message you received from us;
  <br/>
3. at any time by emailing or contacting customer service.
  <br/>
  <br/>
  <br/>
Full list of your rights regarding your Personal Information:
  <br/>
  <br/>
  <br/>
You have the right:
  <br/>
  <br/>
1.  Withdraw your consent to the processing of your personal data at any time;
  <br/>
  <br/>
  <br/>
2. Object to the processing of your personal data. If we process your information in our legitimate interests, such as for direct marketing emails or for our marketing research, you may object. We will consider your request and, in the absence of legal grounds for refusal (for example, public interest or inability to identify you), will stop processing for such purposes;
  <br/>
  <br/>
3. Be informed of what information we keep about you, how we received it and how long we intend to keep it;
  <br/>
  <br/>
4. Check and correct your personal data if it is inaccurate, incomplete or out of date;
  <br/>
  <br/>
5. Restrict the processing of your personal data. If you dispute the accuracy of your personal data, believe that we are processing them illegally, or wish to object to the processing, you have the right to suspend the processing of your personal data temporarily to verify that the processing was consistent. In this case, we will not process personal data for any other purpose than to store it or to comply with the law until the circumstances that led to the restriction have disappeared;
  <br/>
  <br/>
6. Ask us to delete/destroy personal data about you (the right to be forgotten). Please note that the deletion of your personal data may affect your experience with our Services or result in the termination of the relationship between you and us if personal data were strictly required for the provision of services; and
  <br/>
  <br/>
7. Transfer your personal data to another organization (right to data portability). This right applies if we process personal data based on your consent or as part of a contract or contract negotiation and processing is automatic.
  <br/>
  <br/>
8. File a complaint with the supervisory authority.
  <br/>
  <br/>
The rights mentioned above can be realised free of charge by writing us an e-mail address indicated above. In certain cases, we may ask you to confirm your identity before we can act upon your request.
  <br/>
  <br/>
We may transfer your Personal Data if we are obliged to provide it by law.
  <br/>
</p>`,
  privacy_text7: `
  <p>INFORMATION PLACED ON YOUR DEVICE
  <br/>
  <br/>
When you use our services, we may, with your permission, store certain information on your device. This information is called cookies. These are small text files that are stored on your device and remember your preferences when you use our services, visit our websites and online pages.
  <br/>
  <br/>
We also use local objects or «flash cookies». «Flash cookies» are similar to browser cookies. They help us remember your preferences when visiting our websites and store the data needed to play video or audio content.
  <br/>
  <br/>
Neither cookies nor «flash cookies» can be used to access your device or use information on your computer.
  <br/>
  <br/>
Cookies and «flash cookies» are used for analytical purposes only.
  <br/>
  <br/>
We use cookies only to track your usage of our services, remembering your preferences.
  <br/>
  <br/>
Cookies help us track your traffic on our website, improve services for you, facilitate access to the website and increase interest in our services.
  <br/>
  <br/>
We use flash cookies and other cookies to show the most relevant and preferred ads.
  <br/>
  <br/>
KINDS OF COOKIES WE USE
  <br/>
  <br/>
NECESSARY COOKIES
  <br/>
  <br/>
We use cookies to allow any user on our website to navigate the website and use its features, such as accessing secure areas of the website or making financial transactions. Without these cookies, you will not be able to work efficiently on our websites.
  <br/>
  <br/>
COOKIES COLLECTED DURING THE REGISTRATION PROCESS
  <br/>
  <br/>
These cookies contain information collected during your registration; they allow us to learn more about you as a customer and help us provide the right service. We can also use this data to understand your online interests and preferences, making visiting our platforms and services more enjoyable and convenient.
  <br/>
  <br/>
OUR WEBSITE
  <br/>
  <br/>
Our servers use three different types of cookies:
  <br/>
  <br/>
«Temporary» cookie - this type of cookie is stored on your computer while visiting the website. Session-based cookies help you navigate our website more quickly, and if you are a registered customer, this allows us to provide you with the right and relevant information. This cookie is automatically deleted when you close your browser.
  <br/>
  <br/>
«Persistent» cookies - this type of cookie will remain on your computer for a specific time, set for each cookie separately. «Flash cookies» are also saved.
  <br/>
  <br/>
«Analytic» cookies - this type of cookie allows us to recognize and count the number of visitors to our website and see how visitors use our services. This helps us improve the performance of our sites, for example, by allowing you to easily log in and find what you are looking for.
  <br/>
  <br/>
It is up to you to decide, and you always have the choice to agree and accept or disagree with, and refuse to accept cookies.
  <br/>
  <br/>
Most web browsers automatically accept cookies, but if you want, you can change your browser settings to control your cookies.
  <br/>
  <br/>
You can use your web browser to:
  <br/>
  <br/>
1. delete all cookies;
  <br/>
2. block all cookies;
  <br/>
3. allow all cookies;
  <br/>
4. block third-party cookies;
  <br/>
5. clean all cookies when you close your browser;
  <br/>
6. open the session «private viewing»/«incognito», which allows you to browse the Internet without saving local data;
  <br/>
7. install add-ons and plugins to extend browser functions.
  <br/>
  <br/>
  <br/>
Where can I find information about managing cookies?
  <br/>
  <br/>
Internet Explorer cookie information
  <br/>
- <a href="http:/support.microsoft.com/kb/278835" target="_blank">http:/support.microsoft.com/kb/278835</a>   
  <br/>
Chrome cookie information
  <br/>
- <a href="https://support.google.com/accounts/answer/32050" target="_blank">https://support.google.com/accounts/answer/32050</a> 
  <br/>
Firefox cookie information
  <br/>
- <a href="https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored" target="_blank">https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored</a> 
  <br/>
Safari cookie information
  <br/>
- <a href="https://support.apple.com/kb/PH21411?le=en_US" target="_blank">https://support.apple.com/kb/PH21411?le=en_US</a>  
  <br/>
Opera cookie information
  <br/>
- <a href="https://help.opera.com/en/latest/web-preferences/#cookies" target="_blank">https://help.opera.com/en/latest/web-preferences/#cookies</a> 
  <br/>
  <br/>
FLASH COOKIES
  <br/>
  <br/>
You can change Flash Player settings yourself to prevent the use of Flash files. The configuration manager of your Flash Player allows you to make a choice and customize your preferences.
  <br/>
  <br/>
If you decide to completely ban all cookies in your browser, then, unfortunately, you will not be able to use certain resources and services on our sites, and some services will not work correctly, for example, in this case, we will not be able to save the interface language you have chosen.
  <br/>
</p>`,
  privacy_text8: `
  <p>We reserve the right to conduct security checks at any time to confirm the registration details provided by you, and to verify the correctness of the use of our services and financial transactions to prevent possible violations of our Terms of Use of Services and current legislation.
  <br/>
  <br/>
By using our services and services, you agree to our Terms and Conditions of this Policy and allow us to use your personal information to verify the information you provide when registering and using our services, including, if necessary, outside your country.
  <br/>
  <br/>
Security checks may include but are not limited to, filing financial reports and otherwise confirming the personal information you provide to any third-party databases other than ours.
  <br/>
</p>`,
  privacy_text9: `
  <p>We recognise the importance of security and the methods necessary to maintain the confidentiality, integrity and availability of information. We store all Personal Information we receive directly from you in an encrypted and password-protected database on our secure network with state-of-the-art firewall software.
            <br/>
            <br/>
Our services support SSL version 3 with 128-bit encryption.
            <br/>
            <br/>
We also encourage our subsidiaries, agents, partners, affiliates and suppliers to apply the same adequate security measures.
            <br/>
            <br/>
However, sending information over the internet is generally not completely secure and we cannot guarantee you the security of your data while it is in transit.
            <br/>
            <br/>
SpinBet Partners have all the security procedures in place to protect your data once it is received
            <br/>
        </p>`,
  privacy_text10: `
  <p>Our services and website are not intended for persons under the age of 18 or any other age of majority in your state.
            <br/>
            <br/>
Any person who provides information to us through our services and facilities certifies that they are eighteen (18) years old (or the other legal age of majority in your state).
            <br/>
            <br/>
Our company policy includes identifying attempts by minors to gain access to our services and facilities, which may require additional security analysis.
            <br/>
            <br/>
If we become aware that a minor has attempted to provide or has provided us with Personal Information through our services, we will not accept and will delete such information from our databases.
            <br/>
        </p>`,
  privacy_text11: `<p>Personal data is kept for the duration of the business relationship between us or until you ask for your personal data to be deleted.
  <br/>
  <br/>
Your information will be deleted, anonymised or pseudonymised as soon as it is no longer required for the operation of our website.
  <br/>
</p>`,
  privacy_text12: `<p>Personal data collected by us may be stored and processed in any country in which we or our affiliates, suppliers, partners or agents provide the gaming services and facilities of our gaming platform.
  <br/>
  <br/>
By using our services and facilities, you explicitly consent to the transfer of your information outside of your country (including to countries that cannot be assessed as having adequate privacy and personal data protection laws).
  <br/>
  <br/>
However, we take all necessary steps to ensure that our agents, partners, affiliates and suppliers, wherever located, adhere to our privacy standards in general and this Privacy Policy in particular.
  <br/>
</p>`,
  privacy_text13: `<p>We cannot protect information that you provide to a third-party online website linking to our services, or any other information collected by any third-party member of our affiliate programme (if applicable) or by any other means, as those third-party online services and websites are not owned and operated by us and are independent of us.
  <br/>
  <br/>
Any information collected by third parties is governed by the Privacy Policy of the individuals, if any.
  <br/>
</p>`,
  privacy_text14: `<p>If you have any questions about this Privacy Policy or wish to exercise any rights under clause 6 of this Policy, please contact us at: support@spinbet.partners.
            <br/>
        </p>`,
  support_t: `Support:`,
  faq_main_title1: `General Questions`,
  faq_main_title2: `About Product`,
  faq_main_title3: `About the conditions`,
  sub_affiliate_text: `Get from 5% of your partners' NGR earnings`,
  top_geo_title: `TOP GEO`,
  res_geo_title: `RESTRICTED GEO `,
  res_geo_title_mobile: `RESTRICTED GEO`,
  top_country1: `CIS`,
  top_country2: `germany`,
  top_country3: `poland`,
  top_country4: `Portugal`,
  top_country5: `Canada`,
  top_country6: `Australia`,
  top_country7: `New Zealand`,
  top_country8: `Brazil`,
  top_country9: `Turkey`,
  top_country10: `Switzerland`,
  top_country11: `Austria`,
  top_country12: `Czech Republic`,
  res_country1: `BENIN`,
  res_country2: `CAMEROON`,
  res_country3: `IVORY COAST`,
  res_country4: `CURACAO`,
  res_country5: `CYPRUS`,
  res_country6: `FRANCE`,
  res_country7: `GUINEA`,
  res_country8: `IRAN`,
  res_country9: `IRAQ`,
  res_country10: `ISRAEL`,
  res_country11: `LITHUANIA`,
  res_country12: `NEPAL`,
  res_country13: `NETHERLANDS`,
  res_country14: `NORTH KOREA`,
  res_country15: `PUERTO RICO`,
  res_country16: `SOUTH KOREA`,
  res_country17: `Thailand`,
  res_country18: `GREAT BRITAIN`,
  res_country19: `UKRAINE`,
  res_country20: `USA`,
  vertical_translate1: `RevShare<br/>
  up to 60%`,
  vertical_translate2: `CPA<br/>
  up to 150$`,
  vertical_translate3: `Hybrid`,
  vertical_translate4: `Flat<br/> Fee`,
  exclusive_deals: `EXCLUSIVE DEALS`,
};
